---
title: "Project Oriented Workflow"
author: "Chelsey"
date: "5/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(here)
```
```{r}
ca_np <- read.csv(here("data","ca_np.csv"))
```
```{r}
summary(ca_np$visitors)
```
```{r}
ci_np <- read_excel(here("data", "ci_np.xlsx"))
```
```{r}
ggplot(data=ci_np, aes(x=year,y=visitors))+geom_line()
```
```{r}
gg_base <- ggplot(data=ci_np, aes(x=year, y=visitors))
```

```{r}
gg_base+ geom_point()
```
```{r}
gg_base+geom_col()
```
```{r}
gg_base+geom_area()
```
```{r}
gg_base+geom_line(color= "purple", linetype= "dashed")
```
```{r}
gg_base+geom_point(color="purple", pch=17, size=4, alpha=0.5)
```
```{r}
gg_base+geom_point(color="lightcoral", pch=18, size=5, alpha=0.8)
```
```{r}
gg_base+geom_point(aes(size=visitors,color=visitors), alpha=0.5) + theme_minimal()
```
```{r}
gg_base+geom_col(aes(fill=visitors))+ theme_light()
```
```{r}
gg_base+geom_line(linetype="dotted", color= "cornflowerblue")+theme_bw()+labs(
  x="Year",
  y="Annual Park Visitors",
  title="Channel Islands NP Visitors",
  subtitle= "(1963-2016)")
```

```{r}
gg_base+geom_line(color="hotpink")+
  geom_point(color="springgreen", pch=17, aes(size=year),alpha=0.5)
```
```{r}
gg_base+geom_col(color="skyblue", fill="lightpink")+geom_line(color="deeppink")
```
```{r}
ggplot(data=ca_np, aes(x=year,y=visitors))+geom_line()
```
```{r}
ggplot(data=ca_np, aes(x=year, y=visitors, group=park_name))+geom_line(aes(color=park_name))
```
``` {r}
gg_np <- ggplot(data=ca_np, aes(x=year, y=visitors, group= park_name))
```
```{r}
gg_np + geom_line(color="violetred", show.legend=FALSE)+ theme_light()+labs(x="year",y= "annual visitors")+facet_wrap(~ park_name)
```
```{r}
ggsave(here("figures","np_graph.jpg"),dpi=180,width=8,height=7)
```
